<?php
// Official SVN Trunk Rev: 1919
// Error Levels Desciption
$locale['E_ERROR'] = "B³±d krytyczny, zatrzymano wykonywanie skryptu/Fatal Errors halting script execution";
$locale['E_WARNING'] = "B³±d niekrytyczny, kontynuowano wykonywanie skryptu/Non fatal Runtime Errors";
$locale['E_PARSE'] = "B³±d sk³adni PHP/Error generated by parser";
$locale['E_NOTICE'] = "Zdarzenie mog±ce byæ b³êdem/Run-time notices";
$locale['E_CORE_ERROR'] = "B³±d krytyczny podczas uruchomienia PHP/Error during PHP's initial startup";
$locale['E_CORE_WARNING'] = "B³±d niekrytyczny podczas uruchomienia PHP/Warning during PHP's initial startup";
$locale['E_COMPILE_ERROR'] = "B³±d krytyczny zg³oszony przez Zend Engine/Warning generated by zend";
$locale['E_COMPILE_WARNING'] = "B³±d niekrytyczny zg³oszony przez parser/Error generated by parser";
$locale['E_USER_ERROR'] = "B³±d krytyczny zg³oszony przez funkcjê trigger_error()/Error generated by user using trigger_error() function";
$locale['E_USER_WARNING'] = "B³±d niekrytyczny zg³oszony przez funkcjê trigger_error()/Warning generated by user using trigger_error() function";
$locale['E_USER_NOTICE'] = "Informacja zg³oszona przez funkcjê trigger_error()/Notice generated by user using trigger_error() function";
$locale['E_ALL'] = "Pokazuje wszystkie wiadomo¶ci poza E_STRICT/Defines all messages except E_STRICT";
$locale['E_STRICT'] = "";

$locale['err_100'] = "Nd.";
$locale['err_101'] = "<strong>Ostrze¿enie:</strong> W trakcie generowania strony wyst±pi³ b³±d. Sprawd¼ <a href='[ERROR_LOG_URL]'>dziennik b³êdów</a>, aby uzyskaæ wiêcej informacji.";

// Error Managemetn
?>